### ISSUE TITLE
pymodelfit just does not install

### ISSUE THREAD

**Issue by gserrano990** [eteq/pymodelfit#4]
MacOSX Ventura 13.3 
pip 23.0.1
python 3.11

$sudo -H pip install pymodelfit

Collecting pymodelfit
  Downloading PyModelFit-0.1.2.tar.gz (377 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.5/377.5 kB 6.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.10.tar.gz
      Traceback (most recent call last):
        File "/private/tmp/pip-install-emoibrqi/pymodelfit_1022e69095914aadb010e3476073dd5b/distribute_setup.py", line 143, in use_setuptools
          raise ImportError
      ImportError
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/tmp/pip-install-emoibrqi/pymodelfit_1022e69095914aadb010e3476073dd5b/setup.py", line 7, in <module>
          use_setuptools()
        File "/private/tmp/pip-install-emoibrqi/pymodelfit_1022e69095914aadb010e3476073dd5b/distribute_setup.py", line 145, in use_setuptools
          return _do_download(version, download_base, to_dir, download_delay)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/tmp/pip-install-emoibrqi/pymodelfit_1022e69095914aadb010e3476073dd5b/distribute_setup.py", line 123, in _do_download
          tarball = download_setuptools(version, download_base,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/tmp/pip-install-emoibrqi/pymodelfit_1022e69095914aadb010e3476073dd5b/distribute_setup.py", line 193, in download_setuptools
          src = urlopen(url)
                ^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563, in error
          return self._call_chain(*args)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 403: SSL is required
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by gserrano990** [comment]
So what..........9 months later........uhhhhhhh?????????
